package net.gibistash.gtboverlay.util;
import java.util.ArrayList;
public class ShortcutThemes {
    private static final String[] sc = {"Relampago-lightning bolt, lightning, lightning strike, thunder *" ,
            "Fulmine- lightning, lightning strike, lightning bolt" ,
            "Pa- shovel, spade" ,
            "Aquario- aquarium, fish bowl,  fish tank*" ,
            "Raket- rocket, rocketship, missile *" ,
            "Hamburger- burger" ,
            "Cikolata- chocolate, chocolate bar (thank u rat)" ,
            "Balai- broom, broomstick" ,
            "Orage- storm, thunder storm " ,
            "Libreria- bookcase, bookshelf, bookstore*" ,
            "Bibliotheque: library,bookcase,bookshelf,book shelf" ,
            "Regalo, cadeau- present, gifts" ,
            "Noel- santa, christmas" ,
            "Telarana- spider web, cobweb *" ,
            "ragnatela- Spiderweb, web, cobweb *" ,
            "Basen- swimming pool, pool" ,
            "Cubo Magico- rubiks cube, puzzle cube *" ,
            "Velo- bike, bike riding, cycle" ,
            "Polizist- policeman,  police officer" ,
            "Escalar- climbing, rock climbing" ,
            "Ferme- farmhouse,  farm" ,
            "Piment- Chili pepper, chili" ,
            "Campamento- camp,  camping,  campgrounds*" ,
            "Oboz- camp, camping" ,
            "Gummiband- rubber band,  elastic band *" ,
            "Angel- fishing rod" ,
            "Ping pong- table tennis" ,
            "Baralho-deck of cards, pack of cards,  playing cards*" ,
            "Vasodeflores- flowerpot, plant pot, potted plant" ,
            "Handy- cellphone, smartphone *" ,
            "Lapida- gravestone, tombstone *" ,
            "Poubelle- trash can, garbage can, bin, rubbish *               " ,
            "Mulleimer- trash can, garbage can, bin" ,
            "Chips- potato chips,  french fries *" ,
            "Band- tape, tyre, ribbon" ,
            "Cereza, cerise, cereja- cherries, cherry" ,
            "Cela- prison cell, jail cell * " ,
            "Prison-jail " ,
            "Cell- cage" ,
            "Tortuga- turtle, tortoise" ,
            "Casa, dom- house, home" ,
            "Zeilboot- sailing boat, sailboat, sailing *" ,
            "Box of chocolate- box of chocolate, box of chocolates " ,
            "Tnt- dynamite" ,
            "Bauhof- construction yard" ,
            "Orto- vegetable garden" ,
            "Lupa, Lupe- magnifying glass *" ,
            "File-traffic jam, steak" ,
            "Ampoule- lightbulb" ,
            "Faro- lighthouse" ,
            "Eis-ice cream" ,
            "Eisbar-polar bear" ,
            "Eiseimer- ice bucket" ,
            "Eiswaffel - ice cream cone" ,
            "Eiswagen- ice cream van" ,
            "Raketwerper- rocket launcher" ,
            "Grappin/rampino-Grappling hook" ,
            "Fresa-strawberry *" ,
            "Pina-pineapple" ,
            "Steamlocomotive- Steam locomotive *" ,
            "Kiwi-kiwifruit" ,
            "Pizzahawaii - pineapple pizza " ,
            "Glasmelk- glass of milk" ,
            "Glaswasser- cup of water" ,
            "Gla- glass, jar" ,
            "Waterfle- water bottle" ,
            "Fle-bottle" ,
            "Hoja- leaf, leaves, sheet" ,
            "Carta- card, sheet, paper, letter*" ,
            "Scooter- mobility scooter" ,
            "Ketchup-tomato ketchup, ketchup" ,
            "Post- post office" ,
            "Banan- Banana" ,
            "Krant-newspaper" ,
            "Ile- island" ,
            "Ileflottante- floating island" ,
            "Ile deserte- deserted island" ,
            "Auto- automobile, car" ,
            "Torcia- flashlight, torch" ,
            "Gasnica- fire extinguisher*" ,
            "Scala- staircase, scale " ,
            "Kart-go karting" ,
            "Aula- classroom, class" ,
            "洗衣篮-washing basket, laundry basket" ,
            "Wasmand- washing basket, laundry basket *" ,
            "Lampa- genie lamp, lamp" ,
            "Handspinner- fidget spinner" ,
            "Rondo- roundabout" ,
            "Skate- skateboarding" ,
            "Esposa- handcuffs" ,
            "Automat- vending machine" ,
            "Pralka- washing machine" ,
            "Transport-transportation" ,
            "Vervoer- transportation, carriage" ,
            "Mesure/meting- measurement" ,
            "Cookie - chocolate chip cookie (am I high or did we used to have to type “cookie chocolate”)-dino" ,
            "Kassa- cashier, cash register" ,
            "Armario- cabinet, wardrobe, closet, cupboard" ,
            "Lixo- garbage, litter, rubbish, my english teacher" ,
            "Mull- garbage, trash, rubbish" ,
            "Wrak- shipwreck " ,
            "Glass- glass, jar " ,
            "BAD- BATHTUB, BATH (would recommend vanish guessing this)" ,
            "Banera- bathtub, bath, tub" ,
            "Labor- laboratory" ,
            "Panal- honeycomb" ,
            "Pogo- pogo stick" ,
            "Prato- plate, dish, dishes" ,
            "Motyl- butterfly" ,
            "UL- beehive (not ui. dino >.>) WHO TF CALLED ME OUT? PULL UP RIGHT NOW" ,
            "Rup- caterpillar (thanks noticeme Senpai <3)" ,
            "Kapper- hairdresser, hairdressers" ,
            "Chemie- chemistry" ,
            "Kip- chicken" ,
            "Crucero- cruise ship, cruise" ,
            "Pocisk- projectile, bullet" ,
            "Nuta- music note" ,
            "Coco- coconut" ,
            "Sernik- Cheesecake" ,
            "✨KAM✨- hairbrush, comb [IF YOU TOUCH MY K.A.M thing i will bite you- chick]*" ,
            "Escova- hair brush, hairbrush, brush" ,
            "Taran- battering ram " ,
            "Teclado- computer keyboard" ,
            "Keyboard- musical keyboard" ,
            "Rail- train tracks" ,
            "Totem- totem pole" ,
            "Canestro- basketball hoop" ,
            "Obstkorb- fruit basket" ,
            "Zahnfee- tooth fairy" ,
            "Kobold- leprechaun, goblin" ,
            "Hose- trousers" ,
            "Eiffelturm- eiffel tower" ,
            "Sandburg- sand castle" ,
            "Wir- whirlpool" ,
            "Ganek- front porch" ,
            "Orkaan- hurricane" ,
            "Ampel- traffic lights" ,
            "Bruteier- eggs hatching" ,
            "Avion coule- sunken airplane" ,
            "Karton- cardboard box" ,
            "Camera- video camera" ,
            "Hippo- hippopotamus" ,
            "Lina- tightrope" ,
            "Corda- rope, lead, tightrope" ,
            "Gare- train station" ,
            "Cros- cross country " ,
            "Ape- honeybee, bee" ,
            "Hummel- bumblebee " ,
            "Spiwor- sleeping bag" ,
            "Badja- dressing gown" ,
            "Quad- quad bike" ,
            "Tafel- blackboard, table" ,
            "Melo- apple tree" ,
            "Noria- ferris wheel" ,
            "Trampolin- diving board" ,
            "Edente- toothless" ,
            "Mobel- furniture" ,
            "Gartenmobel- garden furniture" ,
            "Lampione- lamp post, street lamp, streetlamp *" ,
            "Peto- chestplate" ,
            "Pilot- remote control" ,
            "O- bone " ,
            "Paisaje- landscape" ,
            "Telefooncel- telephone booth" ,
            "Telefon = telephone / phone" ,
            "Slon- elephant" ,
            "Kerkhof- graveyard" ,
            "Stol- dinner table, table, chair" ,
            "Bolera- bowling alley" ,
            "Moto- motorbike" ,
            "Kipnugget- chicken nugget" ,
            "Kippenjockey- chicken jockey" ,
            "Ladekabel- cellphone charger" ,
            "Ladegerat-Phone charger" ,
            "Pie- foot, feet, dog" ,
            "Headphones-Headphones/headset" ,
            "Caddie- shopping trolley *" ,
            "isimpson- the simpsons " ,
            "Giostre- fairground rides" ,
            "Math- mathematics " ,
            "Sala- living room" ,
            "Mayonesa- mayonnaise " ,
            "Sandia- watermelon" ,
            "Pin- pine tree" ,
            "Laka- grassland" ,
            "Fotograf- photographer" ,
            "Luchtballon- hot air balloon" ,
            "Palma/palme- palm tree" ,
            "Palme- flipper" ,
            "Fon- hairdryer" ,
            "Drive in- drive through " ,
            "Mullwagen- garbage truck" ,
            "Angler- fisherman" ,
            "Pico- pickaxe" ,
            "Fantino, Ruiter- equestrian " ,
            "Ceja- eyebrows, eyebrow" ,
            "Alliance- wedding ring" ,
            "Volante/rat(?)- steering wheel" ,
            "Coliflor- cauliflower" ,
            "Sarten- pan, frying pan" ,
            "Palo- stick" ,
            "Sobre- envelope" ,
            "Turmuhr- clock tower" ,
            "Standuhr- grandfather clock *" ,
            "Brood- loaf of bread, bread" ,
            "Pan- bread" ,
            "Luz- light" ,
            "Collar- necklace " ,
            "Chocolaterie- chocolate factory" ,
            "Serre- greenhouse" ,
            "Lutte- wrestling" ,
            "Nahmaschine- sewing machine" ,
            "Portero, doelman- goalkeeper" ,
            "Cafard- cockroach" ,
            "Sad- orchard *" ,
            "USA- america" ,
            "Saleepepe- salt and pepper" ,
            "Buceo-  scuba diving " ,
            "Pianka- marshmallow" ,
            "Exame- examination" ,
            "Yate- yacht" ,
            "Boda- wedding" ,
            "Cornice- frame/picture frame*, (not photoframe)" ,
            "Fotolijst- picture frame, photoframe" ,
            "Foto- photograph/picture" ,
            "Klimrek- climbing frame " ,
            "Vela- candle, sailing, sail" ,
            "Fiaba- fairytale" ,
            "Bosbrand- forest fire" ,
            "Cascada- waterfall" ,
            "Goma- jellybeans " ,
            "Wekker- alarm clock" ,
            "Sloopkogel- wrecking ball" ,
            "Lapin- bunny, rabbit" ,
            "Lua- moon, the moon" ,
            "Camino- fireplace, chimney, pathway" ,
            "Taller- workshop " ,
            "Achtbaan- rollercoaster" ,
            "Tak- branch, twig" ,
            "Tarea- homework" ,
            "Gemuse- vegetables" ,
            "Rolki, patin- roller blades" ,
            "Kosiarka- lawn mower" ,
            "Lavavetri- window cleaner" ,
            "Pepino- cucumber" ,
            "Klosz- lampshade" ,
            "Teeundkekse- tea and biscuits" ,
            "Pompier- firefighter" ,
            "Hanger- coat hanger " ,
            "Verfpalet- paint palette " ,
            "Saxofon- saxophone " ,
            "Okno- window" ,
            "Schatkist- treasure chest" ,
            "Schat- treasure" ,
            "Calcada- stepping stones, sidewalk" ,
            "Confete- party popper" ,
            "Farbeimer- paint bucket" ,
            "Grill- BBQ grill, barbeque *" ,
            "Tuinfeest- garden party" ,
            "Forderband- conveyor belt" ,
            "Tapisroulant- conveyor belt, treadmill" ,
            "Fosforo- matchstick" ,
            "Glastur- glass door" ,
            "Petard- firecracker" ,
            "Stolek- step stool" ,
            "Helice- propeller" ,
            "Horca- pitchfork " ,
            "Drabinka- step ladder" ,
            "Baie- bay, berry, berries" ,
            "Ferngla- binoculars" ,
            "Visenfriet- fish and chips" ,
            "Eetwedstrijd, eatin’ fight- eating competition" ,
            "Roltrap- escalator" ,
            "Edificio- city building" ,
            "Windmolen- windmill, wind turbine" ,
            "Kregle- bowling pin, bowling" ,
            "Kek- biscuit, cookie, muffin" ,
            "Gieter- watering can" ,
            "Tri- tic tac toe *" ,
            "Bob- bobsledding [seasonal theme]" ,
            "Veer- feather" ,
            "Sap- juice" ,
            "Clip- paperclip" ,
            "Snor- moustache" ,
            "Esmalte- nail polish " ,
            "Laca- hairspray" ,
            "Voetbal - soccer, soccerball" ,
            "Quadro - paint, painting, frame *" ,
            "Diploma - graduation" ,
            "Ambiente - Environment" ,
            "Meta - Finish line, goal" ,
            "Ali- wings" ,
            "Melkweg- milky way" ,
            "Meia- stocking, socks" ,
            "Lolly- lollipop" ,
            "Speelkast- Arcade machine" ,
            "Dorp- village" ,
            "Leer- leather" ,
            "Vat- barrel" ,
            "Berg- Mountain" ,
            "Lacet- shoelaces" ,
            "Spina-  power plug, plug" ,
            "Honkbalveld = baseball field" ,
            "Szpilki = high heels" ,
            "Lavaeimer = lava bucket" ,
            "Kino = movie theater / cinema" ,
            "Post-it = sticky note" ,
            "Espadon = swordfish" ,
            "Spielkonsole = gaming console (might work for variations, haven’t tested)" ,
            "Zahnpasta = toothpaste" ,
            "Patinoire = skating rink" ,
            "Gavettone = water balloon" ,
            "Quadrifoglio = four leaf clover" ,
            "Hashi = chopsticks" ,
            "Damier = checkerboard" ,
            "Kredki = colored pencil" ,
            "Libel= dragonfly" ,
            "Gum- eraser" ,
            "Rug- Carpet" ,
            "Kwal- jellyfish" ,
            "Toque- Chefs Hat" ,
            "Hypnose- hypnotize" ,
            "Bril- glasses, goggles" ,
            "Jewel- crystal" ,
            "Seat- chair/chairs" ,
            "Lift- elevator" ,
            "Blokhut- Log cabin" ,
            "Boxring- boxing ring" ,
            "Radslag- cartwheel" ,
            "Tarnung- camouflage" ,
            "Obru- table cloth" ,
            "Rosal- rose bush" ,
            "Rato- rat, mouse" ,
            "Mikrofon- microphone" ,
            "Red social- social media" ,
            "Ago- needle" ,
            "Pindakaa- peanut butter" ,
            "Stoper- stopwatch" ,
            "Bugel brett- ironing board" ,
            "Paasei- easter egg" ,
            "Paw- peacock" ,
            "Matras- mattress" ,
            "Spagety- spaghetti" ,
            "Parking - car park, parking" ,
            "Remo - rowing, oar" ,
            "Insect - bug, insect" ,
            "King - king, pharaoh" ,
            "Omlet- omelette" ,
            "Pincel- paintbrush" ,
            "Bol- sphere, bowl" ,
            "Sla- cabbage" ,
            "Caribe- caribbean" ,
            "Schaatsen- ice skates, ice skating, skating" ,
            "Drwal- lumberjack" ,
            "Girasol- sunflower" ,
            "Mando- controller" ,
            "Igel - hedgehog" ,
            "Etui- pencil case" ,
            "Games helm- games controller" ,
            "Parkiet- dancefloor" ,
            "U-boot- submarine" ,
            "Peso- weights, dumbbell" ,
            "Fonte- fountain, smelting" ,
            "Magico- magician, magic" ,
            "Patata- potato, potatoes" ,
            "Frappe- smoothie, milkshake" ,
            "Lil’ dog- chihuahua" ,
            "Gaita- harmonica" ,
            "Ra- tree frog" ,
            "Kran- water tap, crane" ,
            "Fullhorn- cornucopia" ,
            "Potd’or- Pot of gold" ,
            "Pod woda- underwater, under the sea" ,
            "Buildin’- construction" ,
            "Paashaa- easter bunny" ,
            "Wensput- wishing well" ,
            "Gluckskeks- fortune cookie" ,
            "Reka- arm, hand" ,
            "Borsa- bag, purse, handbag" ,
            "Lata- can, tin can" ,
            "Tazza- cup, mug" ,
            "Becher- cup, mug, goblet" ,
            "Cabana- hut, cabin, shack" ,
            "Sci- ski, skiing" ,
            "Bank- bench, couch" ,
            "Bife- beef, steak" ,
            "Arbusto- bush, hedge" ,
            "Sapo- frog, toad" ,
            "Usta- lips, mouth" ,
            "Cai- pier, harbor" ,
            "Techo- roof, ceiling" ,
            "Loja- shop, store" ,
            "Neve- snow, snowy" ,
            "Pad- path, pathway, toad" ,
            "Buty- boots, shoes" ,
            "Kajak- kayak, canoe, rowboat" ,
            "Dancar- dance, dancing" ,
            "Hek- fence, witch" ,
            "Musik- music, musical" ,
            "Speer- spear, javelin" ,
            "Inktvi- squid, octopus" ,
            "Cutla- sword, katana" ,
            "Dent- teeth, tooth" ,
            "Saltar- bounce, jumping" ,
            "Luva- gloves, mittens" ,
            "Bubbelbad- hot tub, bubble bath" ,
            "Coccinelle/coccinella- ladybird, ladybug" ,
            "Bandana- hair band, headband" ,
            "Incubo- nightmare" ,
            "Trefbal- dodgeball" ,
            "Vieren- celebrate" ,
            "Lago- lake, pond" ,
            "Pop- doll, puppet" ,
            "Tv- television * " ,
            "Flyin’paper - paper airplane" ,
            "Pommeenor - golden apple" ,
            "Line - line, tightrope" ,
            "Datorskarm - computer screen"};
    public static ArrayList<Integer> findInstanceOf(String bean){
        ArrayList<Integer> indicies = new ArrayList<Integer>();
        int count = 0;
        for(String cheese :sc){
            if(cheese.toLowerCase().contains(bean.toLowerCase())){
                indicies.add(count);
            }
            count++;
        }
        return indicies;
    }
    public static String WordBurger(String theme){
        String ret = "";
        ArrayList<Integer> meats = findInstanceOf(theme);
        for(int i = 0; i < meats.size(); i++){
            ret += sc[meats.get(i)]+"\n";
        }
        if(meats.size()==0){
            return "No such theme/shortcut has been recorded at: https://docs.google.com/document/d/1XaMPUw3uNL08rO1UsZejw0keWvehWxiuOf_c7S8jZGI/edit# 5/28";
        }
        return ret;
    }
}
